[package]
name = "InnerFS"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite = "0.36.1"
serde_yml = "0.0.11"
serde = "1.0.204"
anyhow = "1.0.86"
fuse = "0.3.1"
hmac-sha512 = "1.1.5"
itertools = "0.13.0"
libc = "0.2.155"
time = "0.1.45"
hex = "0.4.3"
log = "0.4.22"