### Home
PROPFIND http://localhost:8080
Content-Type: application/xml
Depth: 0

<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:">
    <D:propall/>
</D:propfind>

### Home and children (1 level)
PROPFIND http://localhost:8080
Content-Type: application/xml
Depth: 1

<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:">
    <D:propall/>
</D:propfind>

###
